run-name: ${{ github.actor }} deployed app
on:
  push:
    branches:
    - main
    
jobs:
  deploy-app-engine:
    runs-on: windows-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: 'projects/262102611503/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'nav-e-387904@appspot.gserviceaccount.com'
      - name: Deploy to app engine
        uses: google-github-actions/deploy-appengine@v1.2.7
        with:
          project_id: 'nav-e-387904'

      
      
    
      
    
  
