run-name: ${{ github.actor }} deployed app
on:
  push:
    branches:
    - main
    
jobs:
  test-server:
    runs-on: windows-latest
    defaults: 
      run:
        working-directory: './server'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: run unit test
        run: python test_app.py
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_KEY }}
          GMAPS_KEY: ${{ secrets.GMAPS_KEY }}
      - name: echo workspace
        run: echo $GITHUB_WORKSPACE
        shell: bash
# TODO: add frontend built unit tests
  # build-frontend:
  #   runs-on: windows-latest
  #   defaults: 
  #     run:
  #       working-directory: './frontend'
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with: 
  #         python-version: '3.11'
  #     - name: Install requirements
  #       run: pip install -r requirements.txt
  #     - name: run unit test
  #       run: python test_app.py
  #       env:
  #         SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_KEY }}
  #         GMAPS_KEY: ${{ secrets.GMAPS_KEY }}
  #     - name: echo workspace
  #       run: echo $GITHUB_WORKSPACE
  #       shell: bash

  deploy-app-engine:
    # only run if test is successful
    needs: 
      - test-server
      # - test-frontend
    runs-on: windows-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: 'projects/262102611503/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'nav-e-387904@appspot.gserviceaccount.com'
          project_id: 'nav-e-387904'
      - name: Deploy server to App Engine
        uses: google-github-actions/deploy-appengine@v1.2.7
        with:
          project_id: 'nav-e-387904'
          working_directory: './server'
          deliverables: './api.yaml'
          env_vars: |-
            SERVICE_ACCOUNT_KEY=${{ secrets.FIREBASE_KEY }}
            GMAPS_KEY=${{ secrets.GMAPS_KEY }}
      - name: build frontend
        run: npm install && npm run build
        working-directory: './frontend'
      - name: Deploy Frontend to App Engine
        uses: google-github-actions/deploy-appengine@v1.2.7
        with:
          project_id: 'nav-e-387904'
          working_directory: './frontend'
          env_vars: |-
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.GMAPS_KEY }}
            NEXT_PUBLIC_MAPS_ID=${{ secrets.MAPS_ID }}

      
      
    
      
    
  
