on:
  pull_request:
    branches:
    - main
    
jobs:
  test-flask:
    runs-on: windows-latest
    defaults: 
      run:
        working-directory: './server'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: run unit test
        run: python test_app.py
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_KEY }}
          GMAPS_KEY: ${{ secrets.GMAPS_KEY }}
      - name: echo workspace
        run: echo $GITHUB_WORKSPACE
        shell: bash
  test-frontend-build:
    runs-on: windows-latest
    defaults: 
      run:
        working-directory: './frontend'
    steps:
      - uses: actions/checkout@v3
      - name: set up nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: echo workspace
        run: echo $GITHUB_WORKSPACE
        shell: bash
        
        
